# Generated by Django 4.1.4 on 2022-12-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_first_name_alter_users_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
