# Generated by Django 4.1.4 on 2022-12-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
