# Generated by Django 4.1.4 on 2022-12-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
